version: "3.7"

networks:
  proxy:
    external: true

volumes:
  purchasing-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/volumes/db
  purchasing-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/volumes/logs


services:
  db:
    image: postgres:13-alpine
    container_name: purchasing-db
    restart: always
    env_file: ./variables.env
    volumes:
      - purchasing-db:/var/lib/postgresql/data
    networks:
      - proxy
  web:
    image: pcdworks/purchasing:latest
    container_name: purchasing
    restart: always
    volumes:
      - purchasing-logs:/app/log
    env_file: ./variables.env
    networks:
      - proxy
    depends_on:
      - db
